# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3908415ab8762b65854ce415a03cffd3"
name = "WHOM Storefront"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_checkouts,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_read_product_tags,unauthenticated_write_checkouts"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
